DROP DATABASE IF EXISTS AddTaskDB;
CREATE DATABASE AddTaskDB;
USE AddTaskDB;

CREATE TABLE persons
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) UNIQUE NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL
);

